import type { NextPage } from 'next'
import dynamic from 'next/dynamic'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import MyEditor from '../components/editor'

const Home: NextPage = () => {
  const [input, setInput] = useState("print(1 + 1);");
  const [result, setResult] = useState("");

  useEffect(() => {
    runCode();
  }, [input]);

  const runCode = async () => {
    const nakRuntime = await import("@nakala-lang/nakjs");
    let res = nakRuntime.wasm_interpret(input);
    setResult(res);
  }
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <MyEditor />
        <textarea onChange={(e) => setInput(e.target.value)} />
        <textarea readOnly value={result} />
      </main>

      <footer >
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span >
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
