import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/header";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Nakala</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="w-3/4">
        <Header
          home
          title="nakala"
          desc="A hobby programming language designed to be fun and familiar - because programming is meant to be fun!"
        />
      </section>

      <article className="prose mt-4">
        <h3 className="font-righteous font-light text-3xl">Philosophy</h3>
        <div>
          <p>Nakala only has two core values:</p>

          <ol>
            <li>The syntax should feel familiar, while remaining unique</li>
            <li>
              {`Nakala doesn't try to do anything really hard, as I want to make
              working on this project fun and not another job that ends up
              burning me out. That doesn't mean it doesn't have cool ideas and
              features though!`}
            </li>
          </ol>
        </div>

        <h3 className="font-righteous font-light text-3xl -mt-1">Features</h3>
        <ul>
          <li>First class functions</li>
          <li>First class classes</li>
          <li>Static type checking</li>
          <li>High performance interpreter (written in Rust 🦀)</li>
          <li>
            Full-featured javascript interpeter via WASM (try the Playground!)
          </li>
          <li>Pretty error messages</li>
        </ul>

        <h3 className="font-righteous font-light -mt-1 text-3xl">
          Planned Features
        </h3>
        <ul>
          <li>Multi-file support via Modules</li>
          <li>Standard library</li>
          <li>FFI support</li>
          <li>Compiler (probably to C++)</li>
          <li>Self-hosted</li>
        </ul>

        <h3 className="font-righteous font-light -mt-1 text-3xl">
          Contributing
        </h3>
        <p>
          I am always welcoming PRs and would love to work on the project with
          other people if they are interested. There are no rules, and I will
          accept any PR as long as it aligns with the projects core values as
          described above.
        </p>

        <div className="h-1 bg-gray-300 w-full my-6" />

        <h3 className="font-righteous font-light -mt-1 text-3xl">History</h3>
        <p>
          {`Nakala started as a programming language that I built based on `}
          <a href="https://arzg.github.io/lang/" className="text-blue-500" target="_blank">{"arzg's Eldiro blog posts"}</a>.
          {`The core architecture (especially the parser) was
          practically identical to Eldiro, hence the name of the project: nakala
          (Punjabi for mimic). If you haven't read through his blog posts, I
          highly recommend you do because it is an unmatched learning resource.`}
          <br /><br/>
          {`I ended up scrapping the entire language and codebase for
          something I built from the ground up after studying more. However, I
          decided to keep the name as a nod to arzg for lighting a spark in me
          that put me on a journey of learning constantly.`}
        </p>
      </article>
    </div>
  );
};

export default Home;
